#include <QApplication>
#include "barwindow.h"

/**
 * @brief Main file.
 * Auto-generated by Qt upon creation of the project. Nothing modified in there.
 */
int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    BARWindow b;
    b.show();
    
    return a.exec();
}
